### PR TITLE
downgrade to net6 and some other cleanup

### PR DESCRIPTION
**Pull request by anthonie-kramer**
* downgrade to net6 so we can use in Elements
* updated make.bat for IFC4 and udpated antlr

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/IFC-gen/77)

### CODE REVIEW

**Review by anthonie-kramer — COMMENTED** [review]
@ikeough this should be pretty straightforward, no other changes except for generated code and updated references

> *[Reviewable](https://reviewable.io/reviews/hypar-io/IFC-gen/77#-:-NhTMQicC2sMahqYluGh:bl0jsgg)* status: 0 of 1 approvals obtained, all discussions resolved (waiting on @ikeough)

**Review by ikeough — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/IFC-gen/77)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @anthonie-kramer)

___
*[`Directory.Build.props` line 5 at r1](https://reviewable.io/reviews/hypar-io/IFC-gen/77#-NhgSUhDA-guLGHECUNS:-NhgSUhDA-guLGHECUNT:b-anvokd) ([raw file](https://github.com/hypar-io/IFC-gen/blob/00453619c388c3bd42002de0f9befd373d8f8177/Directory.Build.props#L5)):*
> ```XML
>         <Authors>Hypar, Inc.</Authors>
>         <Company>Hypar, Inc.</Company>
>         <Copyright>Hypar, Inc. 2020</Copyright>
> ```

Can we update this to 2023?

**Review by anthonie-kramer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/IFC-gen/77)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @ikeough)

___
*[`Directory.Build.props` line 5 at r1](https://reviewable.io/reviews/hypar-io/IFC-gen/77#-NhgSUhDA-guLGHECUNS:-NhgWQR_ECwP9g8RBpI8:b-evaddo) ([raw file](https://github.com/hypar-io/IFC-gen/blob/00453619c388c3bd42002de0f9befd373d8f8177/Directory.Build.props#L5)):*
<details><summary><i>Previously, ikeough (Ian Keough) wrote…</i></summary><blockquote>

Can we update this to 2023?
</blockquote></details>

Done! Also noticed this in the MIT license.

**Review by ikeough — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hypar-io/IFC-gen/77#-:-Ni6Ktp3-D6qZmnKLCRQ:bnfp4nl)* status: 1 of 1 approvals obtained, 1 unresolved discussion

**Pull request merged**
